"""init db

Revision ID: c658bb605a81
Revises: 
Create Date: 2026-06-26 04:25:16.795373

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c658bb605a81"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ohlcv",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("coin", sa.String(length=20), nullable=False),
        sa.Column("timeframe", sa.String(length=10), nullable=False),
        sa.Column("open_time", sa.DateTime(), nullable=False),
        sa.Column("open", sa.DECIMAL(precision=20, scale=8), nullable=True),
        sa.Column("high", sa.DECIMAL(precision=20, scale=8), nullable=True),
        sa.Column("low", sa.DECIMAL(precision=20, scale=8), nullable=True),
        sa.Column("close", sa.DECIMAL(precision=20, scale=8), nullable=True),
        sa.Column("volume", sa.DECIMAL(precision=20, scale=8), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "coin", "timeframe", "open_time", name="uq_ohlcv_coin_timeframe_time"
        ),
    )
    op.create_table(
        "technical_indicators",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("coin", sa.String(length=20), nullable=False),
        sa.Column("timeframe", sa.String(length=10), nullable=False),
        sa.Column("calculated_at", sa.DateTime(), nullable=False),
        sa.Column("rsi_14", sa.DECIMAL(precision=10, scale=4), nullable=True),
        sa.Column("macd_line", sa.DECIMAL(precision=20, scale=8), nullable=True),
        sa.Column("macd_signal", sa.DECIMAL(precision=20, scale=8), nullable=True),
        sa.Column("macd_histogram", sa.DECIMAL(precision=20, scale=8), nullable=True),
        sa.Column("bb_upper", sa.DECIMAL(precision=20, scale=8), nullable=True),
        sa.Column("bb_middle", sa.DECIMAL(precision=20, scale=8), nullable=True),
        sa.Column("bb_lower", sa.DECIMAL(precision=20, scale=8), nullable=True),
        sa.Column("ema_20", sa.DECIMAL(precision=20, scale=8), nullable=True),
        sa.Column("ema_50", sa.DECIMAL(precision=20, scale=8), nullable=True),
        sa.Column("atr_14", sa.DECIMAL(precision=20, scale=8), nullable=True),
        sa.Column(
            "support_levels", sa.ARRAY(sa.DECIMAL(precision=20, scale=8)), nullable=True
        ),
        sa.Column(
            "resistance_levels",
            sa.ARRAY(sa.DECIMAL(precision=20, scale=8)),
            nullable=True,
        ),
        sa.Column("confluence_score", sa.DECIMAL(precision=5, scale=4), nullable=True),
        sa.Column("trend_direction", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "coin", "timeframe", "calculated_at", name="uq_tech_ind_coin_timeframe_time"
        ),
    )
    op.create_table(
        "telegram_channels",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("credibility", sa.DECIMAL(precision=3, scale=2), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "telegram_messages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=True),
        sa.Column("channel_name", sa.String(length=100), nullable=False),
        sa.Column("message_text", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("has_media", sa.Boolean(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("forwards", sa.Integer(), nullable=False),
        sa.Column("reply_count", sa.Integer(), nullable=False),
        sa.Column("coins_mentioned", sa.ARRAY(sa.String(length=20)), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("ingested_at", sa.DateTime(), nullable=False),
        sa.Column("is_processed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["telegram_channels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("telegram_messages")
    op.drop_table("telegram_channels")
    op.drop_table("technical_indicators")
    op.drop_table("ohlcv")
    # ### end Alembic commands ###
