# config/channels.yaml
channels:
  english:
    - "whale_alert"
    - "coingape"
    - "bitcoinist_com"
    - "Cointelegraph"
    - "binance_announcements"
  
  vietnamese:
    - "Coin68News"         # Tin tức cực nhanh tại VN
    - "TapchiBitcoin"      # Kênh tin tức truyền thống
    - "saigontradecoin"    # Cộng đồng trade lớn
    - "hiddengemteam"      # Chuyên săn gem/tin tức altcoin